export default [
    {
        avatar: 'https://cdn.v2ex.com/avatar/cdca/41db/41900_normal.png?m=1644293935',
        "id": "887913",
        content_rendered: ``,
        thankCount:0,
        "title": "正文显示异常12123",
        "node": "经典回顾",
        "username": "经典回顾",
        "date": "几小时前",
    },
    {
        avatar: 'https://cdn.v2ex.com/avatar/cdca/41db/41900_normal.png?m=1644293935',
        "id": "667520",
        content_rendered: ``,
        thankCount:0,
        "title": "嵌套有问题",
        "node": "经典回顾",
        "username": "经典回顾",
        "date": "几小时前",
    },
    {
        avatar: 'https://cdn.v2ex.com/avatar/cdca/41db/41900_normal.png?m=1644293935',
        "id": "724408",
        content_rendered: '',
        thankCount:0,
        "title": "内容超级多",
        "node": "经典回顾",
        "username": "经典回顾",
        "date": "几小时前",
    },
    {
        avatar: 'https://cdn.v2ex.com/avatar/cdca/41db/41900_normal.png?m=1644293935',
        "id": "886622",
        thankCount:0,
        "title": "回复里面如果是 本站帖子，那么不打开新的页面",
        "node": "经典回顾",
        "username": "经典回顾",
        "date": "几小时前",
    },
]